[package]
name = "databases-rust"
version = "0.1.0"
authors = ["Enzo Strongoli <thehazzard@gmail.com>"]
edition = "2018"

[dependencies]
mysql = "16.0.1"
r2d2 = "0.8"
r2d2_mysql = "15.0.0"
failure = "0.1.5"
clap = "2.33"
csv = "1.0"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"